// import { Inter } from 'next/font/google'
import './globals.css'
import { poppins, inter, montserrat, raleway } from "@/lib/fonts";

 


// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${poppins.variable} ${raleway.variable} ${montserrat.variable} ${inter.variable} `}>{children}</body>
    </html>
  )
}
